# Generated by Django 4.1 on 2022-12-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(max_length=128, verbose_name='заголовок')),
                ('text', models.TextField(verbose_name='текст')),
                ('is_publisher', models.BooleanField(default=True)),
                ('description', models.TextField(default='', verbose_name='описание')),
            ],
            options={
                'verbose_name': 'новость',
                'verbose_name_plural': 'новости',
                'db_table': 'news',
            },
        ),
    ]
