# Generated by Django 4.1 on 2022-12-08 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_publisher',
            field=models.BooleanField(default=True, verbose_name='опубликованная'),
        ),
    ]
