# Generated by Django 4.1 on 2022-12-08 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0002_alter_news_date_created_alter_news_is_publisher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='is_publisher',
            new_name='is_published',
        ),
    ]
