# Generated by Django 4.1 on 2022-08-25 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='news',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='app_news.news'),
        ),
        migrations.AlterField(
            model_name='news',
            name='flag_action',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
