# Generated by Django 4.1 on 2022-09-07 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_news', '0004_rename_user_id_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='create_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=36, verbose_name='Город')),
                ('phone_number', models.CharField(blank=True, max_length=12, verbose_name='Номер телефона')),
                ('is_verification', models.BooleanField(default=0, verbose_name='Верифицированный')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Профили пользователей',
                'db_table': 'profile',
            },
        ),
    ]
