# Generated by Django 4.1 on 2022-09-11 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0008_profile_counter_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='create_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_news.profile'),
        ),
    ]
