# Generated by Django 4.1 on 2022-09-11 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0009_alter_news_create_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='create_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_news.profile'),
        ),
    ]
