# Generated by Django 4.1 on 2022-09-11 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0011_tags_news_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(default='', to='app_news.tags', verbose_name='Тег'),
        ),
    ]
