# Generated by Django 4.1 on 2022-11-04 01:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('birthdate', models.DateField(verbose_name='Дата рождения')),
            ],
            options={
                'verbose_name_plural': 'Авторы',
                'db_table': 'authors',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('isbn', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('[0-9-]*')], verbose_name='Книжный номер')),
                ('release', models.IntegerField(validators=[django.core.validators.MinValueValidator(1600), django.core.validators.MaxValueValidator(4000)], verbose_name='Год выпуска')),
                ('page_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество страниц')),
            ],
            options={
                'verbose_name_plural': 'Книги',
                'db_table': 'books',
            },
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_library.author')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_library.book')),
            ],
            options={
                'verbose_name_plural': 'Библиотека',
                'db_table': 'library',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(through='api_library.Library', to='api_library.author'),
        ),
    ]
