# Generated by Django 4.1 on 2022-11-04 01:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_library', '0003_alter_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='birthdate',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1550), django.core.validators.MaxValueValidator(4000)], verbose_name='Дата рождения'),
        ),
    ]
