# Generated by Django 4.1 on 2022-11-04 01:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_library', '0004_alter_author_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[0-9-]*$')], verbose_name='Книжный номер'),
        ),
    ]
