# Generated by Django 4.1 on 2022-12-04 06:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuantityRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(choices=[('1к', '1-комнатная'), ('2к', '1-комнатная'), ('3к', '1-комнатная'), ('4к', '1-комнатная'), ('5к', '1-комнатная'), ('6к', '1-комнатная'), ('С', 'Студия')], default='1к', max_length=2, unique=True, verbose_name='количество комнат')),
            ],
            options={
                'verbose_name': 'Количество комнат',
                'verbose_name_plural': 'Количество комнат',
                'db_table': 'quantity_room',
            },
        ),
        migrations.CreateModel(
            name='SpaceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_type', models.CharField(choices=[('1', 'Жилое'), ('2', 'Нежилое')], default='1', max_length=1, unique=True, verbose_name='тип помещения')),
            ],
            options={
                'verbose_name': 'Тип помещения',
                'verbose_name_plural': 'Типы помещений',
                'db_table': 'space_type',
            },
        ),
        migrations.CreateModel(
            name='Realty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('square', models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='Помещение не может быть меньше 1 м^2')], verbose_name='площадь')),
                ('max_floor', models.PositiveSmallIntegerField(verbose_name='этажей в доме')),
                ('floor', models.PositiveSmallIntegerField(verbose_name='этаж')),
                ('price_per_metre', models.PositiveIntegerField(verbose_name='цена за метр')),
                ('address', models.CharField(max_length=255, verbose_name='адрес')),
                ('is_published', models.BooleanField(default=False)),
                ('quantity_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_realty.quantityroom')),
                ('space_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_realty.spacetype')),
            ],
            options={
                'verbose_name': 'Недвижимость',
                'verbose_name_plural': 'Недвижимость',
                'db_table': 'realty',
            },
        ),
    ]
