# Generated by Django 4.1 on 2022-11-15 01:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=100, validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена')),
                ('remains', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='остаток')),
            ],
            options={
                'verbose_name_plural': 'Товары',
                'db_table': 'goods',
            },
        ),
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='магазин')),
            ],
            options={
                'verbose_name_plural': 'Магазины',
                'db_table': 'shops',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('code', models.CharField(max_length=100, verbose_name='код')),
                ('store', models.ManyToManyField(through='app_shops.Goods', to='app_shops.shops')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_shops.products'),
        ),
        migrations.AddField(
            model_name='goods',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_shops.shops'),
        ),
    ]
